package yuku.alkitab.base.storage.room

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room entity for the many-to-many junction between markers and labels.
 * Lives in [AppDatabase] (file `AlkitabRoomDb`), distinct from the legacy
 * `Marker_Label` table in `AlkitabDb`.
 *
 * Join keys are `marker_gid` and `label_gid` (string GIDs), NOT the
 * autogenerated `_id`s of `marker` / `label`. This is intentional — the
 * sync protocol identifies entities by gid, and a sync that brings down a
 * marker_label may reference markers/labels that haven't been inserted
 * locally yet. Keying on gid keeps the model serializable without a
 * foreign-key dance.
 *
 * Indexes mirror the legacy `Marker_Label` table's three live indexes
 * (`index_Marker_Label_01`, `_02`, and the unique `_04` on `gid`).
 * `index_Marker_Label_03 (marker_gid, label_gid)` was dropped in versionCode
 * 14000172 — preserved as deleted.
 */
@Entity(
    tableName = "marker_label",
    indices = [
        Index(value = ["marker_gid"], name = "index_marker_label_marker_gid"),
        Index(value = ["label_gid"], name = "index_marker_label_label_gid"),
        Index(value = ["gid"], name = "index_marker_label_gid", unique = true),
    ],
)
data class MarkerLabelEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "_id")
    val _id: Long = 0L,
    val gid: String?,
    val marker_gid: String?,
    val label_gid: String?,
)
