apply plugin: 'com.android.library'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    lint {
        abortOnError false
    }

    // We have to specify the ndk version twice, in here and in the main app module
    // https://issuetracker.google.com/issues/353554169
    ndkVersion '28.2.13676358'

    externalNativeBuild {
        ndkBuild {
            path file('jni/Android.mk')
        }
    }
    namespace 'yuku.snappy.codec'
}
