package yuku.alkitab.base.util

object BookAbbrManager {
    val bookAbbrMap: Map<String, String> = mapOf(
        "Kejadian" to "kej",
        "Keluaran" to "kel",
        "Imamat" to "ima",
        "Bilangan" to "bil",
        "Ulangan" to "ula",
        "Yosua" to "yos",
        "Hakim-hakim" to "hak",
        "Rut" to "rut",
        "1 Samuel" to "1sa",
        "2 Samuel" to "2sa",
        "1 Raja-raja" to "1ra",
        "2 Raja-raja" to "2ra",
        "1 Tawarikh" to "1ta",
        "2 Tawarikh" to "2ta",
        "Ezra" to "ezr",
        "Nehemia" to "neh",
        "Ester" to "est",
        "Ayub" to "ayb",
        "Mazmur" to "mzm",
        "Amsal" to "ams",
        "Pengkhotbah" to "pkh",
        "Kidung Agung" to "kid",
        "Yesaya" to "yes",
        "Yeremia" to "yer",
        "Ratapan" to "rat",
        "Yehezkiel" to "yeh",
        "Daniel" to "dan",
        "Hosea" to "hos",
        "Yoel" to "yoe",
        "Amos" to "amo",
        "Obaja" to "oba",
        "Yunus" to "yun",
        "Mikha" to "mik",
        "Nahum" to "nah",
        "Habakuk" to "hab",
        "Zefanya" to "zef",
        "Hagai" to "hag",
        "Zakharia" to "zak",
        "Maleakhi" to "mal",
        "Matius" to "mat",
        "Markus" to "mrk",
        "Lukas" to "luk",
        "Yohanes" to "yoh",
        "Kisah Para Rasul" to "kis",
        "Roma" to "rom",
        "1 Korintus" to "1ko",
        "2 Korintus" to "2ko",
        "Galatia" to "gal",
        "Efesus" to "efe",
        "Filipi" to "fil",
        "Kolose" to "kol",
        "1 Tesalonika" to "1te",
        "2 Tesalonika" to "2te",
        "1 Timotius" to "1ti",
        "2 Timotius" to "2ti",
        "Titus" to "tit",
        "Filemon" to "flm",
        "Ibrani" to "ibr",
        "Yakobus" to "yak",
        "1 Petrus" to "1pe",
        "2 Petrus" to "2pe",
        "1 Yohanes" to "1yo",
        "2 Yohanes" to "2yo",
        "3 Yohanes" to "3yo",
        "Yudas" to "yud",
        "Wahyu" to "wah"
    )
}