package yuku.alkitab.base.util

import yuku.alkitab.base.model.MAudio
import yuku.alkitab.base.model.MVideo

object MediaList {

    val AUDIO = listOf(
        MAudio("TB", "tb_alkitabsuara", "tb", "tb_otnt"),
        MAudio("AYT", "ayt-ai-v2"),
        MAudio("AVB", "avb"),
        MAudio("KJV", "kjv")
    )

    val VIDEOS = listOf(
        MVideo("Ringkasan: Kejadian 1-11", "K_Gd265GYZ4", "Kejadian 1"),
        MVideo("Ringkasan: Kejadian 12-50", "AMvbbGitx3Q", "Kejadian 12"),
        MVideo("Ringkasan: Keluaran 1-18", "BlEk0x7Q8uY", "Keluaran 1"),
        MVideo("Ringkasan: Keluaran 19-40", "3x-zHo7U_WE", "Keluaran 19"),
        MVideo("Ringkasan: Imamat", "bguCNZvhUiQ", "Imamat 1"),
        MVideo("Ringkasan: Bilangan", "GlZpY2VJqPk", "Bilangan 1"),
        MVideo("Ringkasan: Ulangan", "kLwuBAFBNBg", "Ulangan 1"),
        MVideo("Ringkasan: Yosua", "BraD9UPtWGw", "Yosua 1"),
        MVideo("Ringkasan: Hakim-hakim", "0xoJlaPfOiM", "Hakim-hakim 1"),
        MVideo("Ringkasan: Rut", "dHiRnlFu6yo", "Rut 1"),
        MVideo("Ringkasan: 1 Samuel", "FkulFlha45c", "1 Samuel 1"),
        MVideo("Ringkasan: 2 Samuel", "yxNy34ZS0xc", "2 Samuel 1"),
        MVideo("Ringkasan: 1-2 Raja-raja", "f9CRYzJH7es", "1 Raja-raja 1, 2 Raja-raja 1"),
        MVideo("Ringkasan: 1-2 Tawarikh", "_0Xuth1lw44", "1 Tawarikh 1, 2 Tawarikh 1"),
        MVideo("Ringkasan: Ezra-Nehemia", "wWAZHTpSxYg", "Ezra 1, Nehemia 1"),
        MVideo("Ringkasan: Ester", "7gbN2TbmCaM", "Ester 1"),
        MVideo("Ringkasan: Ayub", "6PhUHYInJO4", "Ayub 1"),
        MVideo("Ringkasan: Mazmur", "Gj2ZJSTXE1E", "Mazmur 1"),
        MVideo("Ringkasan: Amsal", "He75ZssdAN0", "Amsal 1"),
        MVideo("Ringkasan: Pengkhotbah", "bzT7jzh2F58", "Pengkhotbah 1"),
        MVideo("Ringkasan: Kidung Agung", "VfhaM-OESHU", "Kidung Agung 1"),
        MVideo("Ringkasan: Yesaya 1-39", "rMvwI5evHwk", "Yesaya 1"),
        MVideo("Ringkasan: Yesaya 40-66", "JKLwf7UQjCc", "Yesaya 40"),
        MVideo("Ringkasan: Yeremia", "HJ6Fws_Kwzo", "Yeremia 1"),
        MVideo("Ringkasan: Ratapan", "FIE-3rb5dbk", "Ratapan 1"),
        MVideo("Ringkasan: Yehezkiel 1-33", "kq29NrX417Q", "Yehezkiel 1"),
        MVideo("Ringkasan: Yehezkiel 34-48", "9zIynmJBMbs", "Yehezkiel 34"),
        MVideo("Ringkasan: Daniel", "KskRV6MWc7c", "Daniel 1"),
        MVideo("Ringkasan: Hosea", "jz_OxntlZHA", "Hosea 1"),
        MVideo("Ringkasan: Yoel", "O_1iFajwdZQ", "Yoel 1"),
        MVideo("Ringkasan: Amos", "DDzzwuKtutw", "Amos 1"),
        MVideo("Ringkasan: Obaja", "kMf4WW1n5Pc", "Obaja 1"),
        MVideo("Ringkasan: Yunus", "GFRXBZQGoPQ", "Yunus 1"),
        MVideo("Ringkasan: Mikha", "-rfYJczXJcU", "Mikha 1"),
        MVideo("Ringkasan: Nahum", "ffnM7hqVfrU", "Nahum 1"),
        MVideo("Ringkasan: Habakuk", "HHztlgmXoDU", "Habakuk 1"),
        MVideo("Ringkasan: Zefanya", "6c_zrjO6Vio", "Zefanya 1"),
        MVideo("Ringkasan: Hagai", "kz62QTe4YAs", "Hagai 1"),
        MVideo("Ringkasan: Zakharia", "CclWiAKZsKI", "Zakharia 1"),
        MVideo("Ringkasan: Maleakhi", "lOzQkLn2joM", "Maleakhi 1"),
        MVideo("Ringkasan: Matius 1-13", "r7wxWUcgf1s", "Matius 1"),
        MVideo("Ringkasan: Matius 14-28", "EZzDp447uk4", "Matius 14"),
        MVideo("Ringkasan: Markus", "UucekJFIQ58", "Markus 1"),
        MVideo("Ringkasan: Lukas 1-9", "vHb9Uw3UzZA", "Lukas 1"),
        MVideo("Ringkasan: Lukas 10-24", "qRR87q9U9x4", "Lukas 10"),
        MVideo("Ringkasan: Yohanes 1-12", "La4OHUqv_D8", "Yohanes 1"),
        MVideo("Ringkasan: Yohanes 13-21", "U73HFzHSkdI", "Yohanes 13"),
        MVideo("Ringkasan: Kisah Para Rasul 1-12", "S73ZmLcr_o8", "Kisah Para Rasul 1"),
        MVideo("Ringkasan: Kisah Para Rasul 13-28", "tAGdzk8N4H0", "Kisah Para Rasul 13"),
        MVideo("Ringkasan: Roma 1-4", "MK2CuUevKU0", "Roma 1"),
        MVideo("Ringkasan: Roma 5-16", "3N-aocQkRt4", "Roma 5"),
        MVideo("Ringkasan: 1 Korintus", "y6NdqCPDC1U", "1 Korintus 1"),
        MVideo("Ringkasan: 2 Korintus", "jqBZFSfYI9E", "2 Korintus 1"),
        MVideo("Ringkasan: Galatia", "KW6RvlHuPSk", "Galatia 1"),
        MVideo("Ringkasan: Efesus", "qtw8IA7949E", "Efesus 1"),
        MVideo("Ringkasan: Filipi", "VH8kBNeiiD0", "Filipi 1"),
        MVideo("Ringkasan: Kolose", "Wg-jSyeleQE", "Kolose 1"),
        MVideo("Ringkasan: 1 Tesalonika", "vLYVfz-9x50", "1 Tesalonika 1"),
        MVideo("Baca Alkitab: 2 Tesalonika", "Og_ogcyWFLY", "2 Tesalonika 1"),
        MVideo("Ringkasan: 1 Timotius", "kBwKFuHfnPU", "1 Timotius 1"),
        MVideo("Ringkasan: 2 Timotius", "MIf5uMPUVXQ", "2 Timotius 1"),
        MVideo("Ringkasan: Titus", "sAcIQp5niYI", "Titus 1"),
        MVideo("Ringkasan: Filemon", "J_zP6hz67zQ", "Filemon 1"),
        MVideo("Ringkasan: Ibrani", "mBdg2ienJSM", "Ibrani 1"),
        MVideo("Ringkasan: Yakobus", "x3KsWUO0NB8", "Yakobus 1"),
        MVideo("Ringkasan: 1 Petrus", "1Ww263guCqo", "1 Petrus 1"),
        MVideo("Ringkasan: 2 Petrus", "2mEabPcQhpc", "2 Petrus 1"),
        MVideo("Ringkasan: 1-3 Yohanes", "UW7gulPRS9s", "1 Yohanes 1, 2 Yohanes 1, 3 Yohanes 1"),
        MVideo("Ringkasan: Yudas", "IgAF9wjpBoE", "Yudas 1"),
        MVideo("Ringkasan: Wahyu 1-11", "f7Sv1sxmtDY", "Wahyu 1"),
        MVideo("Ringkasan: Wahyu 12-22", "3WoyaMsdUck", "Wahyu 12"),
        MVideo("Injil Markus", "W4d66PubwT0", "Markus"),
        MVideo("Kelahiran Yesus: Lukas 1-2", "fmeHRAhG240", "Lukas 1"),
        MVideo("Pembaptisan Yesus: Lukas 3-9", "n5Z1XmEKBYw", "Lukas 3"),
        MVideo("Anak yang Hilang: Lukas 9-19", "eWjW5XrJ_gs", "Lukas 9"),
        MVideo("Penyaliban Yesus: Lukas 19-23", "U2GfARvJK90", "Lukas 19"),
        MVideo("Kebangkitan Yesus: Lukas 24", "46k5-1VCdY0", "Lukas 24"),
        MVideo("Kisah Para Rasul 1-7", "9DJ2aD7zzrw", "Kisah Para Rasul 1"),
        MVideo("Kisah Para Rasul 8-12", "KH9KT20lusA", "Kisah Para Rasul 8"),
        MVideo("Kisah Para Rasul 13-20", "QJ8947npC9Y", "Kisah Para Rasul 13"),
        MVideo("Kisah Para Rasul 21-28", "BHdnptesbWM", "Kisah Para Rasul 21"),
        MVideo("Kitab Kejadian - Bagian 1", "TWMhcg83AWg", "Kejadian 1"),
        MVideo("Kitab Kejadian - Bagian 2", "lxgfSqE4u6g", "Kejadian 12"),
        MVideo("Kitab Keluaran - Bagian 1", "uWnj3fGpDGc", "Keluaran 1"),
        MVideo("Kitab Keluaran - Bagian 2", "AgmSIP_aBs8", "Keluaran 19"),
        MVideo("Kitab Imamat", "yotabRqMvcI", "Imamat 1"),
        MVideo("Kitab Bilangan", "CpINV3k7S_Q", "Bilangan 1"),
        MVideo("Kitab Ulangan", "4z5aY7QPkcM", "Ulangan 1"),
        MVideo("Kitab Ayub", "C3jcMCdVc50", "Ayub 1"),
        MVideo("Kitab Amsal", "n7CqWxmyCPg", "Amsal 1"),
        MVideo("Kitab Pengkhotbah", "3SJTvbMwkBY", "Pengkhotbah 1")
    )


}